### ISSUE TITLE
Force closing the settings app on derpfest, attaching the log

### ISSUE THREAD

**Issue by improbir** [AOSiP/platform_packages_apps_Settings#3]
time: 1564857482048
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.internal.widget.VerifyCredentialResponse.getResponseCode()' on a null object reference
stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.internal.widget.VerifyCredentialResponse.getResponseCode()' on a null object reference
	at com.android.internal.widget.LockPatternUtils.checkCredential(LockPatternUtils.java:377)
	at com.android.internal.widget.LockPatternUtils.checkPassword(LockPatternUtils.java:491)
	at com.android.internal.widget.LockPatternChecker$5.doInBackground(LockPatternChecker.java:236)
	at com.android.internal.widget.LockPatternChecker$5.doInBackground(LockPatternChecker.java:230)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by akhilnarang** [comment]
If its on derpfest, report there
